#!/usr/bin/python3


# backport stuff
import util as ut

def old_main(): # left around as a demo FIXME
    ut.show_args()
    if ut.argc() < 2: return False
    if not ut.check_github_comment_preserving_hooks_enabled(): return False
    
    first_sha = (ut.argv(1))
    
    sha_list = ut.get_sha_list(first_sha)
    ut.emit("sha list: %s" % (str(sha_list)))
    
    if ut.state_file_exists():
        ut.emit("STATE FILE EXISTS: may indicating a previous rebase aborted")
        return False
    else:
        state = dict()
        state['sha_list'] = sha_list
        ut.save_state(state)
        return True
    return False 
def main():
    return True

ut.invoke_hook_main(main)
